# Generated by Django 5.0.4 on 2024-04-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Sobrenome', models.CharField(max_length=50)),
                ('Registro_Empresa', models.IntegerField(max_length=20)),
                ('Escala_de_trabalho', models.DateField()),
            ],
        ),
    ]
